from setuptools import setup

setup(
    name='Python-White-Bear-Editor',
    version='1',
    packages=['.',
              'Constants',
              'Exceptions',
              'Gui',
              'Gui.Dialogs',
              'Gui.Frames',
              'Gui.Panels',
              'Resources',
              'Threads',
              'Tools',
              'Tools.Document',
              'Tools.Document.ArticleElements'],
    package_data={'Resources': ['*.*']},
    install_requires=['wxPython>=4.1.1',
                      'httplib2>=0.19.1',
                      'htmlmin>=0.1.12',
                      'beautifulsoup4>=4.9.3',
                      'tinycss>=0.4',
                      'webcolors>=1.11.1',
                      'lxml>=4.6.3',
                      'paramiko>=2.7.2',
                      'PyYAML>=5.4.1'],
    url='https://github.com/Athwale/Python-White-Bear-Editor',
    license='GNU General Public License v2.0',
    author='Athwale',
    author_email='',
    description='Offline website editor for white-bear web'
)
